# Generated by Django 3.1.2 on 2020-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('denom', models.CharField(max_length=100)),
                ('mint', models.CharField(max_length=100)),
            ],
        ),
    ]
