# Generated by Django 3.1.2 on 2020-10-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('PO', 'Poor'), ('FR', 'Fair'), ('AG', 'Almost Good'), ('G', 'Good'), ('VG', 'Very Good'), ('F', 'Fine'), ('VF', 'Very Fine'), ('XF', 'Extra Fine'), ('AU', 'Almost Good'), ('MS', 'Mint-State'), ('PF', 'Proof'), ('SP', 'Specimen')], default='PO', max_length=2)),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4-6'), ('8', '8-10'), ('12', '12-15'), ('20', '20-25'), ('30', '30-35'), ('40', '40-45'), ('50', '50-58'), ('60', '60-70')], default='1', max_length=2)),
                ('company', models.CharField(choices=[('N', 'NGC'), ('P', 'PCGS'), ('A', 'ANACS'), ('O', 'Other')], default='N', max_length=1)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
            ],
        ),
    ]
