# Generated by Django 3.1.2 on 2020-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='company',
            field=models.CharField(choices=[('N', 'NGC'), ('P', 'PCGS'), ('A', 'ANACS'), ('O', 'Other')], default='N', max_length=1, verbose_name='Grading Company'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='letter',
            field=models.CharField(choices=[('PO', 'Poor'), ('FR', 'Fair'), ('AG', 'Almost Good'), ('G', 'Good'), ('VG', 'Very Good'), ('F', 'Fine'), ('VF', 'Very Fine'), ('XF', 'Extra Fine'), ('AU', 'Almost Good'), ('MS', 'Mint-State'), ('PF', 'Proof'), ('SP', 'Specimen')], default='PO', max_length=2, verbose_name='Letter Grade'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4-6'), ('8', '8-10'), ('12', '12-15'), ('20', '20-25'), ('30', '30-35'), ('40', '40-45'), ('50', '50-58'), ('60', '60-70')], default='1', max_length=2, verbose_name='Numeric Grade'),
        ),
    ]
