# Generated by Django 3.1.2 on 2020-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201007_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='company',
            field=models.CharField(choices=[('N', 'NGC / Numismatic Guaranty Corporation'), ('P', 'PCGS / Professional Coin Grading Service'), ('A', 'ANA / American Numismatic Association Certification Service'), ('O', 'Other')], default='N', max_length=1, verbose_name='Grading Company'),
        ),
    ]
