# Generated by Django 3.1.2 on 2020-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201008_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cac',
        ),
        migrations.AddField(
            model_name='coin',
            name='collection',
            field=models.ManyToManyField(to='main_app.Collection'),
        ),
    ]
