# Generated by Django 3.1.2 on 2020-10-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201008_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='collection',
            new_name='collections',
        ),
    ]
